"""Train command for Souprise.

Provides commands for fine-tuning LLMs with synthetic business data.

License: Apache-2.0
Copyright 2026 Michael Kupermann
"""

import json
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console

from souprise.core.pipeline import DEFAULT_MODELS, resolve_backend
from souprise.data.generators.business import generate_alpaca_training_data

app = typer.Typer(help="Fine-tune LLMs with synthetic business data.")
console = Console()


@app.command()
def generate(
    output_path: str = typer.Option(
        "data/samples/business_training.jsonl",
        help="Path to save the training data"
    ),
    n: int = typer.Option(
        10000,
        help="Number of training examples to generate"
    ),
    seed: int = typer.Option(
        42,
        help="Random seed for reproducibility"
    ),
):
    """Generate synthetic business training data in Alpaca format.

    Example:
        souprise train generate --output my_data.jsonl --n 5000
    """
    console.print("[yellow]Generating synthetic business training data...[/yellow]")

    # Generate data
    training_data = generate_alpaca_training_data(n=n, seed=seed, output_path=output_path)

    # Ensure output directory exists
    output_dir = Path(output_path).parent
    output_dir.mkdir(parents=True, exist_ok=True)

    # Save data
    with open(output_path, "w") as f:
        for item in training_data:
            f.write(json.dumps(item) + "\n")

    console.print(
        f"[green]Generated {len(training_data)} training examples -> {output_path}[/green]"
    )


@app.command()
def create_config(
    output_path: str = typer.Option(
        "soup_config.yaml",
        help="Path to save the Soup configuration"
    ),
    model: Optional[str] = typer.Option(
        None,
        help="Base model for fine-tuning (default: matches the backend)"
    ),
    data_path: str = typer.Option(
        "data/samples/business_training.jsonl",
        help="Path to training data"
    ),
    backend: str = typer.Option(
        "auto",
        help="Backend: 'auto' (detect), 'mlx' (Apple Silicon), 'torch' (CUDA/ROCm/CPU)"
    ),
):
    """Create a Soup configuration file for fine-tuning.

    Example:
        souprise train create-config --backend torch
    """
    backend = resolve_backend(backend)
    model = model or DEFAULT_MODELS[backend]
    config = f"""# Soup configuration for Souprise business LLM fine-tuning
# Generated by: souprise train create-config

base: {model}
task: sft
backend: {backend}

data:
  train: {data_path}
  format: alpaca
  val_split: 0.1

training:
  epochs: 3
  lr: 2e-5
  batch_size: 4
  optimizer: adamw_torch
  lora:
    r: 16
    alpha: 32
    dropout: 0.05
    target_modules: auto
  quantization: 4bit

output: ./souprise_model
"""

    # Save config
    with open(output_path, "w") as f:
        f.write(config)

    console.print(f"[green]Created Soup configuration -> {output_path}[/green]")


@app.command()
def all(
    data_size: int = typer.Option(10000, help="Number of training examples"),
    model: Optional[str] = typer.Option(None, help="Base model (default: matches backend)"),
    backend: str = typer.Option("auto", help="Backend: 'auto', 'mlx', or 'torch'"),
    output_dir: str = typer.Option(".", help="Output directory"),
):
    """Generate training data and config in one command.

    Example:
        souprise train all --data-size 5000
    """
    # Generate data
    data_path = f"{output_dir}/business_training.jsonl"
    generate(n=data_size, output_path=data_path, seed=42)

    # Create config
    config_path = f"{output_dir}/soup_config.yaml"
    create_config(output_path=config_path, model=model, data_path=data_path, backend=backend)

    console.print("[green]Ready to train![/green]")
    console.print(f"  Data: {data_path}")
    console.print(f"  Config: {config_path}")
    console.print("\n  To start training:")
    console.print(f"    soup train --config {config_path}")
